# see https://github.com/marketplace/actions/release-drafter

template: |
  ### SavedDungeonsAndRaids 1.0.6 (2022-Dec-13)
  [Release Notes](https://github.com/kapresoft/wow-saved-dungeons-and-raids/releases/tag/1.0.6) | [Full Changelog](https://github.com/kapresoft/wow-saved-dungeons-and-raids//compare/1.0.5...1.0.6) | [Release Page](https://github.com/kapresoft/wow-saved-dungeons-and-raids/releases)
  
  #### What’s Changed

  $CHANGES
  
  ### Contributors:
  $CONTRIBUTORS
  
  ### Repository: 
  $REPOSITORY
  
  ### ActionbarPlus-1.0.6.zip
  
  ```text
  MD5 <tbd>
  ```
