# see https://github.com/marketplace/actions/release-drafter
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH-alpha'
template: |
  ### SavedDungeonsAndRaids $RESOLVED_VERSION
  [Release Notes](https://github.com/kapresoft/wow-saved-dungeons-and-raids/releases/tag/$RESOLVED_VERSION) | [Full Changelog](https://github.com/kapresoft/wow-saved-dungeons-and-raids/compare/$PREVIOUS_TAG...$RESOLVED_VERSION) | [Release Page](https://github.com/kapresoft/wow-saved-dungeons-and-raids/releases)
  
  #### What’s Changed

  $CHANGES
  
  ### Contributors:
  $CONTRIBUTORS
  
  ### Repository: 
  $REPOSITORY
  
  ### ActionbarPlus-$RESOLVED_VERSION.zip
  
  ```text
  MD5 <tbd>
  ```
