# see https://github.com/marketplace/actions/release-drafter

template: |
  ### SavedDungeonsAndRaids $NEXT_PATCH_VERSION
  [Release Notes](https://github.com/kapresoft/wow-saved-dungeons-and-raids/releases/tag/$NEXT_PATCH_VERSION) | [Full Changelog](https://github.com/kapresoft/wow-saved-dungeons-and-raids//compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION) | [Release Page](https://github.com/kapresoft/wow-saved-dungeons-and-raids/releases)
  
  #### What’s Changed

  $CHANGES
  
  ### Contributors:
  $CONTRIBUTORS
  
  ### Repository: 
  $REPOSITORY
  
  ### ActionbarPlus-$NEXT_PATCH_VERSION.zip
  
  ```text
  MD5 <tbd>
  ```
