# see https://github.com/marketplace/actions/release-drafter
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

template: |
  ### SavedDungeonsAndRaids 1.0.6 (2022-Dec-13)
  [Release Notes]($GITHUB_SERVER_URL/$REPOSITORY/releases/tag/1.0.6) | [Full Changelog]($GITHUB_SERVER_URL/$REPOSITORY/compare/1.0.5...1.0.6) | [Release Page]($GITHUB_SERVER_URL/$REPOSITORY/releases)
  
  #### What’s Changed

  $CHANGES
  
  ### Contributors:
  $CONTRIBUTORS
  
  ### Repository: 
  $REPOSITORY
  
  ### ActionbarPlus-1.0.6.zip
  
  ```text
  MD5 <tbd>
  ```
