# see https://github.com/marketplace/actions/release-drafter

template: |
  ### SavedDungeonsAndRaids ${{ github.ref_name }}
  [Release Notes](https://github.com/kapresoft/wow-saved-dungeons-and-raids/releases/tag/$TAG) | [Full Changelog](https://github.com/kapresoft/wow-saved-dungeons-and-raids/compare/$PREVIOUS_TAG...$TAG) | [Release Page](https://github.com/kapresoft/wow-saved-dungeons-and-raids/releases)
  
  #### What’s Changed

  $CHANGES
  
  ### Contributors:
  $CONTRIBUTORS
  
  ### Repository: 
  $REPOSITORY
  
  ### ActionbarPlus-$TAG.zip
  
  ```text
  MD5 <tbd>
  ```
