--[[

    Please do NOT edit this file.
    The contents of this file will be generated automatically.
    
]]--
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "deDE");
if not L then return end

L["Addon Info"] = "Add-On-Informationen"
L["BINDING_NAME_SDNR_OPTIONS_DLG"] = "Optionen Dialog"

L["COMMAND_CONFIG_TEXT"] = ":: Zeigt die Konfigurationsbenutzeroberfl\195\164che"
L["COMMAND_HELP_TEXT"] = ":: Zeigt diese Hilfe"
L["COMMAND_INFO_TEXT"] = ":: Druckt zus\195\164tzliche Add-On-Informationen"
L["COMMAND_LIST_TEXT"] = ":: Druckt die gespeicherten Dungeons und Raids auf der Konsole"
L["COMMAND_TEXT_FORMAT"] = "%s Initialisiert. Tippe %s auf der Konsole ein, um verf\195\188gbare Befehle anzuzeigen."
L["DUNGEONS"] = "Dungeons"
L["INSTANCES"] = "Instanzen"
L["NO_SAVED_INSTANCES_FOUND"] = "Keine gespeicherte Instanz gefunden"
L["NO_SAVED_RAID_FOUND"] = "Kein gespeicherter Raid gefunden"
L["OPTIONS_LABEL"] = "optionen"
L["RAIDS"] = "Raids"
L["SAVED"] = "Gespeichert"
L["USAGE_LABEL"] = "benutzung"
