name: Delete old workflow runs
on:
  #Run monthly, at 00:00 on the 1st day of month.
  #schedule:
  #  - cron: '0 0 1 * *'
  push:
    tags: [ 100.**" ]
    #branches: [ "main" ]

  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        # see: https://github.com/marketplace/actions/delete-workflow-runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 6
          dry_run: false
