# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: zsh

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install zsh
        run: sudo apt-get update && sudo apt-get install zsh
      - name: Print outputs branch name
        id: vars_branch
        run: echo "::set-output name=branch::${${GITHUB_BRANCH#refs/heads/}//\//-}"
        env:
          GITHUB_BRANCH: "test/1.2.3"
        shell: zsh {0}
      - name: Print branch name
        id: print
        run: echo "${{steps.vars_branch.outputs.branch}}"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo shell is: $SHELL
          echo pwd is: "$(pwd)"
          chmod a+x ./package-addon.sh
          echo "$(ls -l)"
          ./package-addon.sh        

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
