# This is a basic workflow to help you get started with Actions

name: Release Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for tags
  push:
    tags: [ "0.**", "1.**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install zsh
        run: sudo apt-get update && sudo apt-get install zsh
      - name: Print zsh exists
        run: echo "$(which zsh)"
      - name: Setup environment
        # build types: branch, release
        run: |
          echo "build_type=branch" >> $GITHUB_ENV
          echo "build_dir=~/.wow-pre-release" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Build Scripts
        run: |
          echo "Build Type: ${{ env.build_type }}"
          echo Verify zsh exists: "$(which zsh)"
          echo pwd is: "$(pwd)"
          chmod a+x ./release.sh ./package-addon.sh
          ln -s ./release.sh release-wow-addon
          echo "$(ls -l)"

      # Runs a set of commands using the runners shell
      - name: Packaging the addon
        run: |
          echo "Executing: package-addon.sh"
          ./package-addon.sh
      - name: List the build artifacts
        run: |
          echo "Build Artifacts: ${{ env.build_dir }}" 
          echo "$(ls -l ${{ env.build_dir }})"

# end